In [2]:
import pandas as pd # Option/Alt + Enter

In [3]:
df = pd.read_parquet('../assets/sample.parquet')

In [4]:
df

,email,name,gender,created_at,last_visited_at,last_watched_at,recent_watched,viewed_but_not_started,started_but_not_finished,finished,last_email_notification,last_in_app_notification,last_sms_notification
0,b'rickie.6cl60vv5@example.net',b'\xe5\xbd\xad\xe6\x9d\xb0\xe8\xa3\x95',b'unknown',2020-08-10 13:01:25.925310+00:00,2024-05-04 09:50:25.925310+00:00,2024-04-16 14:54:25.925310+00:00,"[106268, 128994, 196316, 102224, 117073, 13499...","[252790, 242198, 242744, 280839, 294537, 25802...","[339290, 338135, 386557, 315086, 360747, 33311...","[414022, 491753, 452195, 473491, 465956, 472922]",2024-03-27 01:27:25.925312+00:00,2024-04-25 20:49:25.925312+00:00,2024-05-04 23:32:25.925313+00:00
1,b'olaf.14ymhjtf@example.org',b'\xe9\xad\x8f\xe7\x92\x87\xe7\x9b\x88',b'unknown',2021-11-13 13:00:25.903489+00:00,2024-04-25 20:57:25.903489+00:00,2024-02-14 23:31:25.903489+00:00,"[129593, 185659, 137946, 180385, 196593, 17247...","[218302, 283484, 235989, 293630, 237616, 24190...","[339192, 346484, 382411, 388275, 331831, 32015...","[484994, 425061, 488919, 422716, 415928, 48465...",2024-03-23 05:16:25.903491+00:00,2024-04-24 02:12:25.903491+00:00,2024-03-11 05:39:25.903491+00:00
2,b'rebecca.3a623w6u@example.com',b'\xe7\x86\x8a\xe7\x95\x85\xe7\x91\x9e',b'unknown',2020-03-27 01:20:25.909394+00:00,2024-04-30 09:06:25.909394+00:00,2024-03-27 18:49:25.909394+00:00,"[198357, 134754, 119650, 143947, 177740, 14936...","[296954, 281003, 207995, 255762, 273740, 28685...","[378858, 371593, 346024, 322289, 311965, 32178...","[462374, 473501, 442656, 488419, 429584, 45729...",2024-04-10 03:39:25.909396+00:00,2024-05-01 06:26:25.909396+00:00,2024-04-20 15:22:25.909396+00:00
3,b'yvonne.qx06kzs6@example.org',b'\xe5\xad\x9f\xe7\x91\x9c\xe6\x98\x95',b'unknown',2022-07-04 00:23:25.871170+00:00,2024-04-10 15:23:25.871170+00:00,2024-02-20 20:54:25.871170+00:00,"[142821, 175799, 148057, 190747, 191670, 13675...","[236812, 233218, 224301, 266233, 219343, 28654...","[376452, 332361, 385716, 379239, 340609, 34413...","[409566, 409169, 417406, 407474, 467075, 43577...",2024-03-26 07:47:25.871172+00:00,2024-04-23 22:56:25.871173+00:00,2024-03-05 19:52:25.871173+00:00
4,b'juston.apls64ti@example.org',b'\xe9\x92\xb1\xe6\x9d\x89\xe6\x99\x96',b'unknown',2023-11-15 00:40:25.923932+00:00,2024-04-18 13:11:25.923932+00:00,2024-05-05 15:42:25.923932+00:00,"[118390, 186827, 141346, 161621, 105315, 13318...","[208463, 215660, 208041, 293861, 283001, 25665...","[309030, 324522, 339998, 382378, 339850, 33021...","[480200, 456941, 488980, 419539, 428889, 43024...",2024-03-22 16:04:25.923934+00:00,2024-04-29 07:57:25.923934+00:00,2024-03-19 09:04:25.923934+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,b'una.inxgk1lq@example.com',b'\xe5\x94\x90\xe4\xba\x91\xe7\x87\x95',b'unknown',2022-05-31 17:23:25.857985+00:00,2024-05-05 11:11:25.857986+00:00,2024-05-05 07:40:25.857986+00:00,"[102858, 150473, 169646, 198344, 188539, 11069...",[229360],"[350932, 354329, 399669, 313982, 360666, 39186...","[451045, 406002, 459253, 443892, 431548, 40493...",2024-04-19 11:08:25.857987+00:00,2024-05-01 03:04:25.857987+00:00,2024-03-02 04:23:25.857987+00:00
996,b'raphaelle.kk6ikbeq@example.net',b'\xe6\x9c\xb1\xe9\xbc\x8e\xe5\xae\x87',b'unknown',2021-02-27 05:09:25.925316+00:00,2024-04-21 06:18:25.925316+00:00,2024-04-09 20:51:25.925316+00:00,"[109703, 149171, 175090, 154961, 153790, 11175...","[220878, 295291, 261087, 226112, 289976, 25493...","[328928, 317839, 341840, 324363, 365354, 34834...","[425399, 406483, 461886, 400037, 486251, 46003...",2024-04-28 01:49:25.925318+00:00,2024-04-29 13:45:25.925318+00:00,2024-05-03 22:50:25.925318+00:00
997,b'josianne.ceoqsbol@example.org',b'\xe8\xb0\xad\xe6\x98\x8e\xe5\x81\xa5',b'unknown',2021-06-05 18:41:25.896514+00:00,2024-05-01 06:13:25.896514+00:00,2024-04-18 00:12:25.896515+00:00,"[168993, 110698, 183276, 166023, 158314, 11443...","[239324, 251864, 244108, 296180, 206157, 27769...","[380531, 346357, 327550, 313397, 300939, 36151...","[402769, 466380, 409562, 493647, 495462, 41201...",2024-03-31 13:49:25.896516+00:00,2024-04-25 17:24:25.896516+00:00,2024-02-23 09:33:25.896516+00:00
998,b'anabel.r5dxwncd@example.com',b'\xe5\xad\x94\xe6\x99\x8b\xe8\xbf\x90',b'unknown',2023-07-31 06:36:25.911201+00:00,2024-04-25 21:26:25.911201+00:00,2024-02-16 16:00:25.911201+00:00,"[147565, 131885, 164655, 182551, 194640, 19049...","[226949, 276896, 258332, 286798, 234990, 20890...","[333249, 301574, 365249, 384525, 391113, 34031...","[487065, 484298, 434654, 490529, 432493, 46817...",2024-03-22 08:00:25.911203+00:00,2024-04-30 05:20:25.911203+00:00,2024-04-06 12:57:25.911203+00:00
999,b'patricia.eft3oxwx@example.org',b'\xe6\x9b\xbe\xe5\xbe\xb7\xe5\x90\x9b',b'unknown',2022-05-17 18:40:25.892196+00:00,2024-04-25 04:18:25.892196+00:00,2024-02-23 22:50:25.892197+00:00,"[183744, 178404, 106294, 117199, 151116, 10032...","[215438, 257781, 265775, 281006, 239472, 26397...","[384153, 346511, 334173, 358981, 361225, 36783...","[422641, 419574, 477235, 455537, 413090, 42208...",2024-04-03 21:05:25.892199+00:00,2024-04-27 12:07:25.892199+00:00,2024-05-04 07:25:25.892199+00:00

In [5]:
df.head()

,email,name,gender,created_at,last_visited_at,last_watched_at,recent_watched,viewed_but_not_started,started_but_not_finished,finished,last_email_notification,last_in_app_notification,last_sms_notification
0,b'rickie.6cl60vv5@example.net',b'\xe5\xbd\xad\xe6\x9d\xb0\xe8\xa3\x95',b'unknown',2020-08-10 13:01:25.925310+00:00,2024-05-04 09:50:25.925310+00:00,2024-04-16 14:54:25.925310+00:00,"[106268, 128994, 196316, 102224, 117073, 13499...","[252790, 242198, 242744, 280839, 294537, 25802...","[339290, 338135, 386557, 315086, 360747, 33311...","[414022, 491753, 452195, 473491, 465956, 472922]",2024-03-27 01:27:25.925312+00:00,2024-04-25 20:49:25.925312+00:00,2024-05-04 23:32:25.925313+00:00
1,b'olaf.14ymhjtf@example.org',b'\xe9\xad\x8f\xe7\x92\x87\xe7\x9b\x88',b'unknown',2021-11-13 13:00:25.903489+00:00,2024-04-25 20:57:25.903489+00:00,2024-02-14 23:31:25.903489+00:00,"[129593, 185659, 137946, 180385, 196593, 17247...","[218302, 283484, 235989, 293630, 237616, 24190...","[339192, 346484, 382411, 388275, 331831, 32015...","[484994, 425061, 488919, 422716, 415928, 48465...",2024-03-23 05:16:25.903491+00:00,2024-04-24 02:12:25.903491+00:00,2024-03-11 05:39:25.903491+00:00
2,b'rebecca.3a623w6u@example.com',b'\xe7\x86\x8a\xe7\x95\x85\xe7\x91\x9e',b'unknown',2020-03-27 01:20:25.909394+00:00,2024-04-30 09:06:25.909394+00:00,2024-03-27 18:49:25.909394+00:00,"[198357, 134754, 119650, 143947, 177740, 14936...","[296954, 281003, 207995, 255762, 273740, 28685...","[378858, 371593, 346024, 322289, 311965, 32178...","[462374, 473501, 442656, 488419, 429584, 45729...",2024-04-10 03:39:25.909396+00:00,2024-05-01 06:26:25.909396+00:00,2024-04-20 15:22:25.909396+00:00
3,b'yvonne.qx06kzs6@example.org',b'\xe5\xad\x9f\xe7\x91\x9c\xe6\x98\x95',b'unknown',2022-07-04 00:23:25.871170+00:00,2024-04-10 15:23:25.871170+00:00,2024-02-20 20:54:25.871170+00:00,"[142821, 175799, 148057, 190747, 191670, 13675...","[236812, 233218, 224301, 266233, 219343, 28654...","[376452, 332361, 385716, 379239, 340609, 34413...","[409566, 409169, 417406, 407474, 467075, 43577...",2024-03-26 07:47:25.871172+00:00,2024-04-23 22:56:25.871173+00:00,2024-03-05 19:52:25.871173+00:00
4,b'juston.apls64ti@example.org',b'\xe9\x92\xb1\xe6\x9d\x89\xe6\x99\x96',b'unknown',2023-11-15 00:40:25.923932+00:00,2024-04-18 13:11:25.923932+00:00,2024-05-05 15:42:25.923932+00:00,"[118390, 186827, 141346, 161621, 105315, 13318...","[208463, 215660, 208041, 293861, 283001, 25665...","[309030, 324522, 339998, 382378, 339850, 33021...","[480200, 456941, 488980, 419539, 428889, 43024...",2024-03-22 16:04:25.923934+00:00,2024-04-29 07:57:25.923934+00:00,2024-03-19 09:04:25.923934+00:00

In [6]:
df.describe()

,email,name,gender,created_at,last_visited_at,last_watched_at,recent_watched,viewed_but_not_started,started_but_not_finished,finished,last_email_notification,last_in_app_notification,last_sms_notification
count,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000,1000
unique,1000,986,1,NaN,NaN,NaN,1000,1000,1000,1000,NaN,NaN,NaN
top,b'rickie.6cl60vv5@example.net',b'\xe8\xb4\xba\xe6\xad\x86\xe7\xbf\xa0',b'unknown',NaN,NaN,NaN,"[106268, 128994, 196316, 102224, 117073, 13499...","[252790, 242198, 242744, 280839, 294537, 25802...","[339290, 338135, 386557, 315086, 360747, 33311...","[414022, 491753, 452195, 473491, 465956, 472922]",NaN,NaN,NaN
freq,1,2,1000,NaN,NaN,NaN,1,1,1,1,NaN,NaN,NaN
mean,NaN,NaN,NaN,2021-10-09 05:35:14.679931+00:00,2024-04-20 02:20:28.419932+00:00,2024-03-21 16:13:20.859932+00:00,NaN,NaN,NaN,NaN,2024-04-13 12:33:36.519935+00:00,2024-04-28 12:04:34.659935+00:00,2024-03-22 19:39:08.619935+00:00
min,NaN,NaN,NaN,2019-05-09 17:59:25.896589+00:00,2024-04-05 22:00:25.918907+00:00,2024-02-05 23:43:25.890142+00:00,NaN,NaN,NaN,NaN,2024-03-21 23:04:25.898566+00:00,2024-04-20 21:57:25.880638+00:00,2024-02-05 22:49:25.902055+00:00
25%,NaN,NaN,NaN,2020-08-07 10:13:55.910072+00:00,2024-04-12 13:05:10.914987+00:00,2024-02-27 19:17:40.903912+00:00,NaN,NaN,NaN,NaN,2024-04-02 06:44:40.922277+00:00,2024-04-24 18:25:40.922133+00:00,2024-02-29 09:52:40.903386+00:00
50%,NaN,NaN,NaN,2021-10-28 09:11:55.888797+00:00,2024-04-19 14:55:25.860416+00:00,2024-03-21 18:33:55.910706+00:00,NaN,NaN,NaN,NaN,2024-04-13 15:48:25.906306+00:00,2024-04-28 16:02:25.910561+00:00,2024-03-23 23:35:25.910755+00:00
75%,NaN,NaN,NaN,2022-12-01 03:48:25.913309+00:00,2024-04-27 08:49:40.917345+00:00,2024-04-13 00:48:10.914209+00:00,NaN,NaN,NaN,NaN,2024-04-24 10:38:10.905018+00:00,2024-05-02 05:10:40.905725+00:00,2024-04-15 04:08:25.906340+00:00
max,NaN,NaN,NaN,2024-02-05 03:50:25.903207+00:00,2024-05-05 21:39:25.884749+00:00,2024-05-05 21:41:25.922599+00:00,NaN,NaN,NaN,NaN,2024-05-05 21:28:25.925031+00:00,2024-05-05 21:51:25.908007+00:00,2024-05-05 16:03:25.903613+00:00

In [10]:
df[df['created_at'] >= '2024-01-25'] # select * from df where created_at >= '2024-01-25'

,email,name,gender,created_at,last_visited_at,last_watched_at,recent_watched,viewed_but_not_started,started_but_not_finished,finished,last_email_notification,last_in_app_notification,last_sms_notification
12,b'candelario.k09qbm2w@example.net',b'\xe5\x91\xa8\xe9\xb8\xbf\xe6\x89\xbf',b'unknown',2024-01-29 03:30:25.926680+00:00,2024-04-12 22:26:25.926680+00:00,2024-02-21 21:20:25.926680+00:00,"[129130, 183764, 126327, 165360, 114153, 14707...","[209778, 295265, 292251, 227251, 243123, 27751...","[368802, 328397, 310306, 330958, 361881, 30524...","[468941, 473960, 494944, 416015, 416976, 48032...",2024-03-25 13:58:25.926681+00:00,2024-04-21 11:31:25.926682+00:00,2024-04-23 23:22:25.926682+00:00
26,b'meghan.zfz2xq8m@example.org',b'\xe5\x94\x90\xe7\x80\x9a\xe5\x90\x9b',b'unknown',2024-01-31 07:49:25.897247+00:00,2024-04-14 09:03:25.897247+00:00,2024-02-22 02:31:25.897248+00:00,"[106332, 136533, 162763]","[221994, 274190, 203003, 258132]","[328699, 317730, 322226, 331095, 364938, 30969...","[404041, 403140, 428037]",2024-05-05 08:23:25.897248+00:00,2024-04-30 14:41:25.897249+00:00,2024-02-09 21:13:25.897249+00:00
240,b'theresia.qffrdky6@example.net',b'\xe5\xb4\x94\xe5\xbd\xac\xe9\x94\x90',b'unknown',2024-02-05 03:50:25.903207+00:00,2024-04-28 09:32:25.903207+00:00,2024-03-09 13:20:25.903207+00:00,"[111996, 137611, 115212, 122468, 101856, 12805...","[221404, 220027, 220353, 257174, 241009, 22829...","[396663, 399583, 367705, 361750, 316238, 39058...","[404606, 424298, 407493, 481086, 404507, 41181...",2024-04-20 02:58:25.903210+00:00,2024-05-01 09:52:25.903210+00:00,2024-04-12 23:50:25.903210+00:00
491,b'gaston.ar4k3eld@example.org',b'\xe6\x9b\xbe\xe5\x93\xb2\xe5\x8d\x97',b'unknown',2024-01-27 16:29:25.906346+00:00,2024-04-14 03:10:25.906346+00:00,2024-04-01 11:42:25.906346+00:00,"[192995, 192224, 151478, 108210, 159061, 19296...","[213448, 251633, 201604, 288205, 223729, 24900...","[390139, 307102, 389460, 357621, 323068, 33200...","[413331, 470361, 401156, 470256, 402536, 47895...",2024-03-25 03:07:25.906347+00:00,2024-05-02 06:32:25.906347+00:00,2024-03-07 03:25:25.906348+00:00
630,b'vesta.ogpio1y5@example.org',b'\xe4\xbb\x98\xe9\xbe\x99\xe5\xbe\xb7',b'unknown',2024-02-01 04:42:25.891426+00:00,2024-04-23 14:30:25.891426+00:00,2024-02-17 12:09:25.891426+00:00,"[145438, 156496, 114852, 121073, 190656, 18604...","[201621, 276264, 244972, 256725, 229254, 26239...","[355332, 398011, 388709, 349423, 353001, 36847...","[493637, 412070, 447540]",2024-05-03 22:45:25.891428+00:00,2024-04-29 22:52:25.891428+00:00,2024-04-27 11:54:25.891428+00:00
712,b'broderick.nw0o1x33@example.net',b'\xe8\x92\x8b\xe9\xbb\x9b\xe4\xba\xa6',b'unknown',2024-01-28 01:28:25.854014+00:00,2024-04-13 04:45:25.854014+00:00,2024-03-26 03:52:25.854015+00:00,"[100168, 154415, 144146, 149103, 153222, 124592]","[262567, 234647, 266344, 293099, 200169, 27985...","[322944, 347279, 391878, 358380, 338446, 326028]","[421075, 467306, 447920, 408402, 410014, 45724...",2024-03-29 11:26:25.854016+00:00,2024-05-04 12:05:25.854016+00:00,2024-03-21 21:16:25.854016+00:00

In [13]:
df[df['created_at'] >= '2024-01-25'].count()

email                       6
name                        6
gender                      6
created_at                  6
last_visited_at             6
last_watched_at             6
recent_watched              6
viewed_but_not_started      6
started_but_not_finished    6
finished                    6
last_email_notification     6
last_in_app_notification    6
last_sms_notification       6
dtype: int64